//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingManagement.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceDetail
    {
        public int Id { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public Nullable<int> NewsPaperId { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<int> NumberOfCopies { get; set; }
        public Nullable<decimal> Cost { get; set; }
    
        public virtual NewsPaper NewsPaper { get; set; }
        public virtual Invoice Invoice { get; set; }
    }
}
