//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingManagement.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManualBulkSupply
    {
        public int Id { get; set; }
        public Nullable<int> NewsPaperId { get; set; }
        public Nullable<int> NumberOfCopies { get; set; }
        public Nullable<System.DateTime> SupplyDate { get; set; }
    
        public virtual NewsPaper NewsPaper { get; set; }
    }
}
