//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingManagement.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsPaperRate
    {
        public int Id { get; set; }
        public Nullable<int> NewsPaperId { get; set; }
        public Nullable<System.DateTime> Startdate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<decimal> Sunday { get; set; }
        public Nullable<decimal> Monday { get; set; }
        public Nullable<decimal> Tuesday { get; set; }
        public Nullable<decimal> Wednesday { get; set; }
        public Nullable<decimal> Thursday { get; set; }
        public Nullable<decimal> Friday { get; set; }
        public Nullable<decimal> Saturday { get; set; }
    
        public virtual NewsPaper NewsPaper { get; set; }
        public virtual User User { get; set; }
    }
}
